### ISSUE TITLE
does not show discount for price types other then public price

### ISSUE THREAD

**Issue by userodoo** [gisce/openobject-addons#1]
i have created additional Price fields for products (list_price_usd, List_price_gbp, List_price_eur)

and then created price types for each one then created a price list and choose the base price for each product with the related discount 

when creating a sales order i get can see the original price and discount for products with the public pricelist type 

but when choose a product with different base pricelist type then the discount is not visible and i see directly the the final price

and sometimes i receive the below error

**Comment by ecarreras** [comment]
This is not the official addons for OpenERP go to https://github.com/odoo/odoo
